dev: Yes

instance: GAM2

default_host: http://ec2-204-236-198-80.compute-1.amazonaws.com/

database:
#    dbn: mysql
#    db: mindovermedia
#    user: root
#    password: ''
#    host: localhost
    dbn: mysql
    db: gam2
    user: gam
    password: 'gam'
    host: 127.0.0.1

memcache:
    address: 0.0.0.0
    port: 11222

beanstalk:
    address: 0.0.0.0
    port: 11238
    
email:
    host: smtp.gmail.com
    port: 587
    username: myimapaccount@gmail.com
    password: mypwd

facebook:
    app_id = '177033235680785'

twitter:
    consumer_key = 's5Ex8SQqsxoWtrbcs1lkA'
    consumer_secret = 'ztHbfXDfYAavLnpi9sXnvuVZLZ6UAnD5U5efyiqbI'