dev: Yes

app_mode: NOTbeta
app_env: dev

instance: ChangeByUs-dev

default_host: http://localhost:8080/
blog_host: http://ec2-184-73-83-52.compute-1.amazonaws.com/

database:
    dbn: mysql
    db: gam2
    user: gam
    password: 'gam'
    host: 127.0.0.1

memcache:
    address: 0.0.0.0
    port: 11222

beanstalk:
    address: 0.0.0.0
    port: 11238
    
email:
    host: smtp.gmail.com
    port: 587
    username: changebyusnyc@gmail.com
    password: tr4f!0ma
    from_email: nyc@changeby.us
    from_name: 'Change by Us NYC'

twilio:
    sid: AC2f8000ed6b6560de2f1f6b6bf962280a
    token: XXXXXXX
    api: 2010-04-01
    phone: "6463928258"
    
facebook:
    app_id: '204545712900061'
    #app_id: '177033235680785'

twitter:
    consumer_key: '7z7vETOzJPXZLicXieelfQ'
    consumer_secret: 'kaIzFN21IxUPewEcgervVMefjBqMM5PwKu0bw7LKcU'
    request_token_url: 'http://twitter.com/oauth/request_token'
    access_token_url: 'http://twitter.com/oauth/access_token'
    authenticate_url: 'http://twitter.com/oauth/authenticate'
    #consumer_key: 's5Ex8SQqsxoWtrbcs1lkA'
    #consumer_secret: 'ztHbfXDfYAavLnpi9sXnvuVZLZ6UAnD5U5efyiqbI'
    #request_token_url: 'http://twitter.com/oauth/request_token'
    #access_token_url: 'http://twitter.com/oauth/access_token'
    #authenticate_url: 'http://twitter.com/oauth/authenticate'