dev: Yes

app_mode: not-beta
app_env: dev

instance: ChangeByUs-dev

default_host: http://localhost:8080/
blog_host: http://dev-nycblog.changeby.us/

database:
    dbn: mysql
    db: gam2
    user: root
    password: 'xxxx'
    host: 127.0.0.1

memcache:
    address: 0.0.0.0
    port: 11222

beanstalk:
    address: 0.0.0.0
    port: 11238
    
email:
    host: smtp.gmail.com
    port: 587
    username: changebyusnyc@gmail.com
    password: xxxx
    from_email: nyc@changeby.us
    from_name: 'Change by Us NYC'

twilio:
    sid: AC2f8000ed6b6560de2f1f6b6bf962280a
    token: XXXXXXX
    api: 2010-04-01
    phone: "6463928258"
    
facebook:
    app_id: '204545712900061'
    #app_id: '177033235680785'

twitter:
    consumer_key: 'xxx'
    consumer_secret: 'xxx'
    request_token_url: 'http://twitter.com/oauth/request_token'
    access_token_url: 'http://twitter.com/oauth/access_token'
    authenticate_url: 'http://twitter.com/oauth/authenticate'
    
aws:
    access_key_id: xxx
    secret_access_key: xxx
    bucket: eholda-nyc-changebyus
    
media:
    isS3mirror: True
    root: http://s3.amazonaws.com/demo-nyc-changebyus/data/giveaminute/   