dev: Yes

app_mode: not-beta
app_env: dev

instance: ChangeByUs-dev

default_host: http://localhost:8080/
blog_host: http://dev-nycblog.changeby.us/

database:
    dbn: mysql
    db: gam2
    user: gam
    password: 'gam'
    host: 127.0.0.1

memcache:
    address: 0.0.0.0
    port: 11222

beanstalk:
    address: 0.0.0.0
    port: 11238
    
email:
  # Common configuration

  # This needs to be an email address that has been validated by SES
  # run ./ses-verify-email-address.pl -k ~/.aws/localprojects/awsCredentials -l
  # and 
  # ./ses-verify-email-address.pl -k ~/.aws/localprojects/awsCredentials -v newaddr@localprojects.net
  from_email: nyc@changeby.us
  from_name: 'Change by Us NYC'
  
  # If both SMTP and AWS_SES are enabled then the system uses AWS first, and if 
  # the aws send quota is close then we switch over to SMTP
   
  # SMTP specific configuration. 
  smtp:
    host: smtp.gmail.com
    port: 587
    username: 'changebyusnyc@gmail.com'
    password: 'tr4f!0ma'
    # Generally TLS is necessary for gmail. So set it here
    starttls: True
  
  # Amazon SES - only used if smtp is disabled!
  aws_ses:
    access_key_id: AKIAIUP6UG5LN4CTQS7A
    secret_access_key: 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
    
twilio:
    sid: AC2f8000ed6b6560de2f1f6b6bf962280a
    token: XXXXXXX
    api: 2010-04-01
    phone: "6463928258"
    
facebook:
    app_id: '204545712900061'
    #app_id: '177033235680785'

twitter:
    consumer_key: '7z7vETOzJPXZLicXieelfQ'
    consumer_secret: 'kaIzFN21IxUPewEcgervVMefjBqMM5PwKu0bw7LKcU'
    request_token_url: 'http://twitter.com/oauth/request_token'
    access_token_url: 'http://twitter.com/oauth/access_token'
    authenticate_url: 'http://twitter.com/oauth/authenticate'
    #consumer_key: 's5Ex8SQqsxoWtrbcs1lkA'
    #consumer_secret: 'ztHbfXDfYAavLnpi9sXnvuVZLZ6UAnD5U5efyiqbI'
    #request_token_url: 'http://twitter.com/oauth/request_token'
    #access_token_url: 'http://twitter.com/oauth/access_token'
    #authenticate_url: 'http://twitter.com/oauth/authenticate'
